name: Tests

on:
  push:
    branches:
      - '1.*'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4]
        laravel: ['5.5.*', '5.8.*', '6.*']

    name: 'PHP ${{ matrix.php }} / ${{ matrix.laravel }}'

    steps:
      - uses: actions/checkout@master

      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: '${{ matrix.php }}'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: none

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Composer dependencies
        run: composer require "illuminate/support:${{ matrix.laravel }}"

      - name: Show laravel version
        run: composer show laravel/framework

      - name: Install Dependencies
        run: npm install

      - name: Compile Assets
        run: npm run prod

      - name: Run tests
        run: ./vendor/bin/phpunit
